import { OutageStatus } from "@prisma/client";
import { prisma } from "../../../../../lib/prisma.js";

export const get = async (req, res) => {
  let outage;
  try {
    outage = await prisma.outage.findUnique({
      where: {
        id: req.params.outageId,
      },
      include: {
        failures:
          req.query.includeFailures && req.query.includeFailures === "true"
            ? {
                select: {
                  id: true,
                  status: true,
                  autogeneratedMessage: true,
                  reason: true,
                  createdAt: true,
                },
                orderBy: {
                  createdAt: "desc",
                },
              }
            : false,
        comments:
          req.query.includeComments && req.query.includeComments === "true"
            ? {
                include: {
                  user: {
                    select: {
                      name: true,
                    },
                  },
                },
              }
            : false,
      },
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }

  res.json(outage);
};
