-- CreateEnum
CREATE TYPE "Icon" AS ENUM ('GITHUB', 'TWITTER', 'LINKEDIN', 'INSTAGRAM', 'FACEBOOK', 'YOUTUBE', 'DISCORD', 'SLACK', 'PHONE', 'EMAIL', 'WEBSITE', 'BLOG', 'PAYMENT', 'BTC', 'ETH', 'DRIBBBLE');

-- CreateEnum
CREATE TYPE "OutageStatus" AS ENUM ('OPEN', 'CLOSED');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'DEV');

-- CreateEnum
CREATE TYPE "FailureReason" AS ENUM ('STATUS_CODE', 'REQUEST_FAILURE', 'EXPECTED_TEXT', 'LATENCY', 'NO_RESPONSE');

-- CreateEnum
CREATE TYPE "SubscriptionTier" AS ENUM ('FREE', 'LAUNCH', 'PRO');

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Workspace" (
    "id" STRING NOT NULL,
    "name" STRING NOT NULL,
    "subdomain" STRING,
    "headerLinkId" STRING,
    "footerMessage" STRING,
    "showsPingpalLogo" BOOL NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "stripeCustomerId" STRING,
    "stripeSubscriptionId" STRING,
    "tier" "SubscriptionTier" NOT NULL DEFAULT 'FREE',

    CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Service" (
    "id" STRING NOT NULL,
    "name" STRING NOT NULL,
    "domain" STRING NOT NULL,
    "expectedText" STRING,
    "expectedStatus" INT8 NOT NULL,
    "method" STRING NOT NULL,
    "body" STRING,
    "headers" STRING,
    "maxLatency" INT8 NOT NULL,
    "checkInterval" INT8 NOT NULL,
    "lastCheck" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Hit" (
    "id" STRING NOT NULL,
    "latency" INT8 NOT NULL,
    "serviceId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Hit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Failure" (
    "id" STRING NOT NULL,
    "status" INT8,
    "headers" STRING,
    "body" STRING,
    "latency" INT8,
    "autogeneratedMessage" STRING NOT NULL,
    "reason" "FailureReason" NOT NULL,
    "collectBody" BOOL NOT NULL DEFAULT false,
    "collectHeaders" BOOL NOT NULL DEFAULT false,
    "serviceId" STRING NOT NULL,
    "outageId" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Failure_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Outage" (
    "id" STRING NOT NULL,
    "status" "OutageStatus" NOT NULL DEFAULT 'OPEN',
    "serviceId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Outage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Comment" (
    "id" STRING NOT NULL,
    "text" STRING NOT NULL,
    "userId" STRING NOT NULL,
    "outageId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Link" (
    "id" STRING NOT NULL,
    "text" STRING NOT NULL,
    "url" STRING NOT NULL,
    "icon" "Icon",
    "footerWorkspaceId" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Link_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_UserToWorkspace" (
    "A" STRING NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Workspace_subdomain_key" ON "Workspace"("subdomain");

-- CreateIndex
CREATE UNIQUE INDEX "Workspace_headerLinkId_key" ON "Workspace"("headerLinkId");

-- CreateIndex
CREATE UNIQUE INDEX "_UserToWorkspace_AB_unique" ON "_UserToWorkspace"("A", "B");

-- CreateIndex
CREATE INDEX "_UserToWorkspace_B_index" ON "_UserToWorkspace"("B");

-- AddForeignKey
ALTER TABLE "Workspace" ADD CONSTRAINT "Workspace_headerLinkId_fkey" FOREIGN KEY ("headerLinkId") REFERENCES "Link"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Service" ADD CONSTRAINT "Service_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Hit" ADD CONSTRAINT "Hit_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Failure" ADD CONSTRAINT "Failure_outageId_fkey" FOREIGN KEY ("outageId") REFERENCES "Outage"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Failure" ADD CONSTRAINT "Failure_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Outage" ADD CONSTRAINT "Outage_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_outageId_fkey" FOREIGN KEY ("outageId") REFERENCES "Outage"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "Link" ADD CONSTRAINT "Link_footerWorkspaceId_fkey" FOREIGN KEY ("footerWorkspaceId") REFERENCES "Workspace"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "_UserToWorkspace" ADD CONSTRAINT "_UserToWorkspace_A_fkey" FOREIGN KEY ("A") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_UserToWorkspace" ADD CONSTRAINT "_UserToWorkspace_B_fkey" FOREIGN KEY ("B") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
